### PR TITLE
Minor PR - add else statement at the end

### PR DESCRIPTION
**Pull request by KaraMelih**
Only a minor change at the end to the decider.
We were checking the `_id` and deciding whether we should reset the cache, retract from cache, or add to coincidence lists.
I just cleaned a little, and added `else: print(f"{id} is not supported")` line

### CODE REVIEW

**Comment by KaraMelih** [comment]
@Storreslara could you please have a look and merge if you see it fits? 
It is just a  few lines that were bothering me earlier

**Comment by Storreslara** [comment]
Looks good to me ! Thanks

**Comment by Storreslara** [comment]
lol sorry didn't mean to close it

**Comment by KaraMelih** [comment]
Normally, if the user uses the `snews_pt` we assign this field however, in case someone tries to publish -a- dictionary using `hop.Stream` we should warn that cs does not support this.

Actually still, if a user submits a dictionary that does not have `"_id"` it will raise `"snews_message does not have any field called _id"` kind of error. Maybe we should consider also fixing that

**Pull request merged**
